WIP: Export view
csehlke/EiDiA pull request #25
Opened 2020-06-11 11:57 UTC by Neihtq

- created richtext editor with ```draft-js```
- added inlinestyle features: italic, bold, underlined, strikethrough
- setup UI for inlinestyle features: EditorTools
- setup UI for Export-View componentes: RightSidepanel

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/DocEditor.js
> +  ];
ich hätte das in eine extra Datei ausgelagert, nachdem wir das ja mindestens 2x verwenden

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/DocEditor.js
> +        };
gibt es einen Grund warum die Funktionen hier im Construktor stehen und nicht außerhalb?

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/DocEditor.js
> +                    onChange={onChange}
hätte die Konstanten direkt rein geschrieben, ist aber Geschmackssache

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/EditorTools.js
> +import FormatUnderlinedIcon from '@material-ui/icons/FormatUnderlined';
ist die Frage ob wir hier auch gleich schon auf dei react-icons wechseln sollten

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/EditorTools.js
> +                <IconButton onMouseDown={() => this.logClick("alighn justify")}>
*align* -> Typo

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/EditorTools.js
> +                <IconButton onMouseDown={() => this.handleClick("align riht")}>
*right* -> typo

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/RightSidepanel.js
> +          <div/>
gibt es einen Grund für dieses div?

2020-06-11 20:33 UTC, csehlke commented on package.json
> +    "@material-ui/icons": "^4.9.1",
statt denen die react-icons verwenden

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/views/ExportView.js
> +        this.setState({["editorState"]: editorState})
müsste das nicht `this.setState({editorState: editorState})` sein?

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/views/ExportView.js
> +          ["editorState"]: RichUtils.toggleInlineStyle(this.state.editorState, inlineStyle)
müsste das nicht `this.setState({editorState: RichUtils.toggleInlineStyle(this.state.editorState, inlineStyle)})` sein?

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/views/ExportView.js
> +                    </Column>
um die Sidebar brauchst du dich hier nicht kümmern, die kommt von 'oben'

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/views/ExportView.js
> +                            ref={(docEditor) => {this.docEditor = docEditor}}
ich hätte `ref={this.docEditor}` geschrieben, oder wird das an andere Stelle neu assigned

2020-06-11 20:33 UTC, csehlke commented on EiDiA_frontend/src/views/ExportView.js
> +                            editorState={editorState}
gleiche wieder mit der Constante hier

2020-06-11 20:43 UTC, csehlke requested changes

2020-06-11 20:43 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/EditorTools.js
> +                    <FormatAlignCenterIcon />
hier fehlen jeweils die style änderungen

2020-06-11 20:48 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/EditorTools.js
> +                <IconButton onMouseDown={() => this.logClick("alighn justify")}>
und warum logClick und nicht handleClick?

2020-07-07 16:18 UTC, Neihtq commented on EiDiA_frontend/src/views/ExportView.js
> +                            ref={(docEditor) => {this.docEditor = docEditor}}
Meine toggle inlinestyle funktion funktioniert sonst nicht mehr. Die referenz vom DocEditor brauch ich für diese Funktion

2020-07-11 17:11 UTC, csehlke commented
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `SetValueSection`. See https://fb.me/react-warning-keys for more information.
    in WithStyles(ForwardRef(TableRow)) (created by SetValueSection)
    in SetValueSection (created by RightSidePanel)
    in div (created by RightSidePanel)
    in RightSidePanel (created by ExportMainView)
    in div (created by styled.div)
    in styled.div (created by ExportMainView)
    in div (created by styled.div)
    in styled.div (created by ExportMainView)
    in div (created by ExportMainView)
    in ExportMainView (created by ExportView)

2020-07-11 17:12 UTC, csehlke commented
Uncaught TypeError: documentData[documentIndex] is undefined
    mapValues ExportMainView.js:154
    componentDidUpdate ExportMainView.js:268

2020-07-11 17:21 UTC, csehlke commented
ch glaube du musst im "Edit" verbieten im Dokument Änderungen im Text selber zu machen, das mach dir den Text kaputt, wenn du dannach Variablen ersetzt

2020-07-11 17:43 UTC, csehlke commented
was hältst du davon die drei Seitennamen als Constanten zu declarieren?

2020-07-11 18:27 UTC, csehlke commented
in den DialogWindows fehlt die Möglichkeit einen Record aus zu wählen => wollen wir die überhaupt einem Record zuordnen oder zumindest die Templates global speichern?

2020-07-11 18:51 UTC, csehlke requested changes
Hab bis jetzt die Hälfte angeschaut, der Rest kommt später

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/support files/constants.js
> +export const fontSizes = [
unused code

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/views/ExportView.js
> +        this.props.setTitle(this.state.currentPage);
ich hätte hier als Hauptüberschrift "Create Document" gesetzt, denn die andere Info steckt ja in der Unterüberschrift

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/views/ExportView.js
> +        this.setState({currentPage: page, readOnly: (page=="Select Template")});
Vergleiche immer mit 3 = siehe #65

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Header.js
> +    };
lots of unused code L 34-43

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Header.js
> +                        <div onClick={() => props.changeView("Select Template")}>Select Template</div>
Gibt es einen Grund warum das "onClick" nicht schon im Typography drin ist?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Header.js
> +        //boxShadow: "0px 0px 4px 0px rgba(0,0,0,0.75)"
unused code

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Header.js
> +        marginRight: theme.spacing(2)
menueButton wird nie genutzt

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +    return documentData;
add a TODO if not implemented

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +        this.editorText = llorem["Template 0"];
ist das nicht auch Teil vom State?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +        this.actionSet = {
magst du hier kommentieren was das ist?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +const components = {
magst du hier kommentieren was das ist?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +            selectedDocs: [],
was sicher gut wäre, hier Beispielausprägungen zu kommentieren

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +            selectedDocs: [],
für sowohl variables als auch selecetedDocs

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +        selectedDocs.forEach((name) => { if (name in documents) documentData.push(documents[name])});
was passiert hier?
falls hier etwas identifiziert werden soll, warum nicht by Id sonder by Name?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +                let tmp = k.split("/");
tmp ist ein schlechter Name, wenn das ein anderer nochmal verstehen soll... tmp-was

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +                let tmp = k.split("/");
und auch variable und value sind auch nur sinnvoll, wenn es tatsächlich um die Variablen im Document geht

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +    addToList(element) {
addSelectedDocumentToList

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +            let value = (k in currVariables) ? currVariables[k]["value"] : newVariables[k]["value"];
ist geschmackssache, aber hier müsste ja jeweils auch `newVariables[k].value` gehen nachdem wir erst ein Array und dann ein Object haben

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +        const arr = value.split(" ");
value und arr, es gibt sicher sprechendere Namen

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +            if (this.props.currentPage == "Edit") this.mapValues();
```suggestion
        if (this.props.currentPage !== prevProps.currentPage && this.props.currentPage == "Edit") {
            this.mapValues();
```

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +            open: false,
What is open? Gibt es keinen sprechenderen Namen dafür?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +        comp3: "setValueSection"
Wenn man an dieser Stelle schon die Componenten einsetzte, spart man sich später das Mapping im RightSidepanel

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +                    </Column>
Spricht was degegen nur 2 Spalten zu machen?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +        />);
inline wahrscheinlich die schönere Lösung: also
```
{props.currentPage === "Select Template" ? "" : <FloatingWindow.../>}
```

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/DocEditor.js
> +        this.editor = editor;
ist Editor kein State?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +                            comp3={componentSet.comp3}
warum nicht einfach das gesamte Object `componentSet` übergeben?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +                            onAction3_3={actionSet.onAction3_3 || null}
und dann schon bei der deklaration die dritte action=null setzten

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/FloatingWindow.js
> +        this.setState({search: event.target.value.substr(0,20)});
warum begranzt auf 20 Zeichen?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/FloatingWindow.js
> +            <Dialog onClose={this.props.onClose} fullWidth={true} maxWidth={'lg'} id="temp" aria-labelledby="simple-dialog-title" open={this.props.open}>
warum `id="temp" aria-labelledby="simple-dialog-title"`

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/ExportDocumentWindow.js
> +    margin: 0 5% 0 5%;
`margin: 0 5%`
ist identisch

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/ExportDocumentWindow.js
> +        let selectedDocs = this.props.selectedDocs;
die Variablen brauchts nicht

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/Preview.js
> +        let editorState = this.props.editorState;
variable ohne Mehrwert

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/ExportDocumentWindow.js
> +                        {selectedDocs.map((doc) => <FormControlLabel control={<Checkbox color="primary"/>} label={doc}/>)}
die Variable müsste eher usedDocs statt selectedDocs heißen, weil ausgewählt habe ich sie ja noch nicht

wird auch irgendwo gespeichert welche Dokumente ich im Dialog ausgewählt habe?

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/ExportDocumentWindow.js
> +                        <div width="80%">
es gibt kein width attribute auf einem div, das muss in ein style eingepackt werden

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/ExportDocumentWindow.js
> +                            <Input placeholder="Search Records ..." fullWidth={true}  inputProps={{ 'aria-label': 'description' }} value={this.props.value} onChange={this.props.updateSearch.bind(this
description ist eher nicht das richtige Label

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/ExportDocumentWindow.js
> +                        </Button>
ale die Funktionen die wir nicht implementieren sollten wir vielleicht disablen

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/ExportDocumentWindow.js
> +    height: 50%;
height 50% funktionier nicht ganz, evtl klappt max-height

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/SaveTemplateWindow.js
> +    height: 50%;
same here wie im anderen ExportDocumentWindow

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/SaveTemplateWindow.js
> +                        </Box>
die Box hier ähnlich wie im anderen Window mit der Preview ersetzten

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/Subcomponents/SaveTemplateWindow.js
> +                            <div width="80%">
Width auf div geht nicht

2020-07-11 18:51 UTC, csehlke commented on EiDiA_frontend/src/components/ExportView/styles.css
> +
wird die Datei irgendwo verwendet ich habe keinen Import gefunden?

2020-07-14 14:10 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +        selectedDocs.forEach((name) => { if (name in documents) documentData.push(documents[name])});
```name``` zu ```docName``` 
weil selectedDocs Dokumentennamen enthält und nach denen identifiziert wird

2020-07-14 14:22 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +                let tmp = k.split("/");
umbenannt zu
```
let variableTokens
let docVariable
let indexString
let documentIndex
let indices
let docValue
```

2020-07-14 14:24 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +            let value = (k in currVariables) ? currVariables[k]["value"] : newVariables[k]["value"];
struktur nochmal grundlegend geändert

2020-07-14 14:26 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +        const arr = value.split(" ");
umbenannt:
```
const value --> const editorText
const arr --> tokenizedText
```

2020-07-14 14:38 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +            open: false,
umbenannt zu ```showDialog```: ne bool flag die entscheidet ob der Dialog/FloatingWindow angezeigt wird oder nicht (Save Template, Export Document)

material-ui's Dialog component verwendet die open flag für diese Funktion, von daher in der FloatingWindow class folgendes drin:
```<Dialog ... open={this.props.showDialog}> ```

2020-07-14 14:48 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +                    </Column>
nicht wirklich ... wollte links bisschen frei fläche haben, damit der editor mittig ist.

2020-07-14 15:05 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/Subcomponents/DocEditor.js
> +        this.editor = editor;
angepasst, war copy&paste von vorherigen versionen

2020-07-14 15:12 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/ExportMainView.js
> +                            onAction3_3={actionSet.onAction3_3 || null}
wie meinst du das? auf der Edit view hat die dritte sub component 3 actions

2020-07-14 15:15 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/FloatingWindow.js
> +        this.setState({search: event.target.value.substr(0,20)});
war glaub ich von philipps Filecabint damals übernommen. Aber da es nicht fix ist, ob beim export die dokumente in einem Record gespeichert werden und eig die templates global gespeichert werden, habe ich das file cabinet aus dem window gelöscht und damit auch diese funktion.

2020-07-14 15:16 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/FloatingWindow.js
> +            <Dialog onClose={this.props.onClose} fullWidth={true} maxWidth={'lg'} id="temp" aria-labelledby="simple-dialog-title" open={this.props.open}>
war copy paste, habs gelöscht

2020-07-14 15:17 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/Subcomponents/ExportDocumentWindow.js
> +    margin: 0 5% 0 5%;
FlexRow entfernt

2020-07-14 15:22 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/Subcomponents/ExportDocumentWindow.js
> +                        {selectedDocs.map((doc) => <FormControlLabel control={<Checkbox color="primary"/>} label={doc}/>)}
habs geändert zu ```usedDocs```

im Dialog ausgewählte Dokumente werden jetzt im state gespeichert.

2020-07-14 15:26 UTC, Neihtq commented on EiDiA_frontend/src/components/ExportView/styles.css
> +
hab die datei gelöscht

2020-07-15 11:27 UTC, csehlke requested changes
erste Drittel, mehr folgt

2020-07-15 11:27 UTC, csehlke commented on EiDiA_backend/src/controllers/exportTemplate.js
> +            res.status(200).json({response: dummyData});
```suggestion
            res.status(200).json({exportTemplates: dummyData});
```

2020-07-15 11:27 UTC, csehlke commented on EiDiA_backend/src/controllers/exportTemplate.js
>  };
warum nicht wie hier #59

2020-07-15 11:27 UTC, csehlke commented on EiDiA_backend/src/routes/exportTemplate.js
> +router.get('/search/:query', middleWares.checkAuthentication, ExportTemplateController.search);
warum nicht wie in #59

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/support files/constants.js
> +`;
magst du das in das in die Datei vom Philipp verschieben?

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/support files/constants.js
> +const BASE_URL = "http://localhost:3000/";
das gibt es schon im constants.js im root folder

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/support files/constants.js
> +}
das gehört näher zur Export View, evtl ist das gut aufgehoben in ExportView.js

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/support files/constants.js
> +}
und das hier hätte ich in deinen Backend Controler geschrieben, oder wird das noch wo anders verwendet? Dann vielleicht für alle einheitlich herausziehen und nach constants.js im root folder

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/components/filetable/FileTable.js
> +}
weg damit, der Filetable ist inzwischen in den record folder gewandert

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/Header.js
> +                    Select Template
use the constants

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/Header.js
> +                    Edit Template
same here

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/Header.js
> +                    Edit
same

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/Header.js
> +const MenuAppBar = (props) => {
ist MenuAppBar der richtige Name? es geht ja nicht um die App sindern um die ExportView => `ExportMenuBar`?

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/ExportMainView.js
> +}
Warum nicht inline?

2020-07-15 11:27 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/ExportMainView.js
> +            this.selectTemplate(initTemplate.name, initTemplate.id);
was passiert wenn du ein `response: []` vom backend bekommst, oder ist das irgendwo anders abgefangen?

2020-07-15 13:26 UTC, csehlke commented
Variablen gehen verloren wenn:
select template -> move to "Edit" -> replace one variable -> move back to edit Template (variable is gone) -> move to "Edit" (variable cannot be changed anymore")

2020-07-15 13:34 UTC, csehlke commented
es ist sicher sinnvoll die Ordnerstruktur etwas anzu passen:
- components
  - export
    - dialog
      - everything to the dialgs
    - edit
      - everything to the right Side for edit
    - editTemplate
      - everything to the right Side for edit template
    - selectTemplate
      - everything to the right Side for select template
    - everything else
  - ...

2020-07-15 15:02 UTC, csehlke requested changes

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/ExportMainView.js
> +                            onAction3_3={actionSet.onAction3_3}
warum das actionSet nicht ähnlich zum componentSet?

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/HeaderExport.js
> +"use strict";
ist die Datei nicht an der falschen Stelle? ich häte die in den Ordner exportView verschoben

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/HeaderExport.js
> +const MenuAppBar = (props) => {
?? der Dateiname ist HeaderExport aber die Component heißt MenuAppBar?

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/HeaderExport.js
> +const MenuAppBar = (props) => {
-> wird nicht mehr genutzt -> entfernen

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/SaveTemplateWindow.js
> +                    <Input placeholder="Template Name" inputProps={{'aria-label': 'description'}}/>
```suggestion
                    <Input placeholder="Template Name"/>
```
`description` ist keine Beschreibung

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/SaveTemplateWindow.js
> +export default class SaveTemplateSection extends React.Component {
Filename und componet name stimmen nicht überein

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/SaveTemplateSection.js
> +            <div>
brauchts das surrounding div?

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/SaveTemplateWindow.js
> +                    <Input placeholder="Template Name" inputProps={{'aria-label': 'description'}}/>
und vielleicht irgendeinen Hinweis in der GUI darstellen: not implemented, nachdem es ja noch nicht tut, da ua die Eingabe nirgends gespeichert wird

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/ExportDocumentWindow.js
> +        let usedDocs = this.props.selectedDocs;
warum nicht inline?

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/ExportDocumentWindow.js
> +        let usedDocs = this.props.selectedDocs;
und das prop zu usedDocs umbenennen, oder?

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/ExportDocumentWindow.js
> +                        <Input placeholder="Template Name"/>
Für was gebe ich hier einen Namen ein, wenn der nirgends weiter verwendet wird?

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/ExportDocumentWindow.js
> +                            label={doc}/>)}
hier fehlt irgendwie der value für die checkbox, oder?

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/ExportDocumentWindow.js
> +        newState.selectedDocs.push(doc);
heißt ich kann ein Document nicht mehr aus der Liste holen und mt "select -> unselect -> select" zwei mal in die Liste bringen

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/SetValueSection.js
> +                </div>
zum einen warum ein zusätzliches Div
zum anderen warum ist das nicht auch eine einzelne Componente wie bei den anderen Ansichten auch

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/TemplateList.js
> +                console.log(error);
error statt err -> !

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/DocSearch.js
> +    search(e) {
hast du einen schöneren Namen für e?

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/EditorTools.js
> +        newState.alignments[alignmentStyle] = newFlag;
```suggestion
        newState.alignments[alignmentStyle] = true;
```

für alignment braucht man eine andere Strategie, sonst haben wir am ende überhaupt kein alignment ausgewählt

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/EditorTools.js
> +        e.preventDefault()
aus `e` macht `event` ;)

wann braucht man das `preventDefault()`, evtl muss man das überall sonst noch nachtragen

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/EditorTools.js
> +    setInlineStyle(e, inlineStyle) {
aus e macht event ;)

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/EditorTools.js
> +    setInlineStyle(e, inlineStyle) {
gilt auch für den Rest der datei

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/VariableList.js
> +                    {variableKeys.map((key) => <li key={key}>{key}</li>)}
weißt du ob s für die li elemente eine Möglichkeit gibt die Punkte zu entfernen? Denn aktuell hast du abgeschnittene Punkte in der UI

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/SetValueSection.js
> +function convertData(variables, value = null) {
```suggestion
function convertData(variables) {
```

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/SetValueSection.js
> +                <FormControl style={{margin: "5px"}}>
```suggestion
                <FormControl style={{margin: "5px", width: '100%', padding: '0 10px 0 0'}}>
```
fixes the dropdown's width

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/ExportMainView.js
> +        variableState[newState.selectedVariable].source = value;
```suggestion
        variableState[newState.selectedVariable].source = 'user';
```
make it obvious that the user entered this value

2020-07-15 15:02 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/SetValueSection.js
> +                    <Table aria-label="simple table">
```suggestion
                    <Table>
```

2020-07-16 16:28 UTC, Neihtq commented on EiDiA_frontend/src/components/exportView/subcomponents/SetValueSection.js
> +                </div>
zusätzliche div gelöscht,

du meinst ein extra component für den Button? Bei Edit TemplateView wird die dritte/unterste Component aus der variablenliste und dem button bestehen (änderung ist im anderne branch drin). Nur bei Select Template besteht die dritte component aus den zwei Buttons. Generell sind die Components in den drei Flächen des RightSidePanels unterteils.

2020-07-16 16:31 UTC, Neihtq commented on EiDiA_frontend/src/components/exportView/subcomponents/VariableList.js
> +                    {variableKeys.map((key) => <li key={key}>{key}</li>)}
Ich hab keine abgeschnittenen Punkte bei mir. Kannst du mir ein Screenshot zeigen? Außerdem hab ich in nem anderen Branch die Breite vom Rightside panel und von der Variablenliste fixiert. Die momentane Größenregelung könnte mit den abgeschnittenen Punkten bei dir zusammenhängen.

2020-07-16 16:36 UTC, Neihtq commented on EiDiA_frontend/src/components/exportView/subcomponents/EditorTools.js
> +        e.preventDefault()
preventDefault() ist notwendig wenn man inlinestyle oder alignmentstyle über den button click ändert während der editor fokussiert war. Der Fokus geht ohne preventDefault() verloren und die ausgewählten Styleänderungen treten nicht ein.

2020-07-18 08:16 UTC, csehlke commented on EiDiA_frontend/src/components/exportView/subcomponents/VariableList.js
> +                    {variableKeys.map((key) => <li key={key}>{key}</li>)}
![grafik](https://user-images.githubusercontent.com/29836078/87848353-c82ee480-c8df-11ea-8c0d-0528da78b622.png)

2020-07-18 08:39 UTC, csehlke requested changes

2020-07-18 08:39 UTC, csehlke commented on .vscode/settings.json
> +}
gitignore

2020-07-18 08:39 UTC, csehlke commented on EiDiA_frontend/src/components/HeaderExport.js
> +"use strict";
todo

2020-07-18 08:39 UTC, csehlke commented on EiDiA_frontend/src/support files/constants.js
> +}
todo

2020-07-18 08:39 UTC, csehlke commented on EiDiA_frontend/src/components/HeaderExport.js
> +const MenuAppBar = (props) => {
todo

2020-07-18 08:39 UTC, csehlke commented on EiDiA_frontend/src/components/HeaderExport.js
> +const MenuAppBar = (props) => {
todo

2020-07-18 08:39 UTC, csehlke commented on EiDiA_frontend/src/components/export/selectTemplate/TemplateList.js
> +        })
es graucht auch ein catch
```suggestion
        })
        .catch(error => console.log(error));
```

2020-07-18 13:56 UTC, Neihtq commented on EiDiA_frontend/src/components/exportView/subcomponents/VariableList.js
> +                    {variableKeys.map((key) => <li key={key}>{key}</li>)}
hab margin gesetzt damit die li elemente weiter rechts sind

2020-07-18 14:34 UTC, csehlke approved these changes

2020-07-18 14:36 UTC, merged