advanced search
csehlke/EiDiA pull request #27
Opened 2020-06-17 20:42 UTC by csehlke

2020-06-17 20:43 UTC, csehlke commented on EiDiA_frontend/src/components/search/SearchForm.js
> +            value: 1, // todo revert to 0
TODO

2020-06-21 14:48 UTC, csehlke commented
![grafik](https://user-images.githubusercontent.com/29836078/85227649-1505c500-b3df-11ea-9fe3-5b0fb5819195.png)

2020-07-06 19:00 UTC, thetommes requested changes

2020-07-06 19:00 UTC, thetommes commented on EiDiA_frontend/src/assets/CompareTypes.js
> +    {type: 'number', name: 'smaller or equal than', id: 305, fields: 1},
```suggestion
    {type: 'number', name: 'greater than', id: 302, fields: 1},
    {type: 'number', name: 'greater than or equal to', id: 303, fields: 1},
    {type: 'number', name: 'less than', id: 304, fields: 1},
    {type: 'number', name: 'less than or equal to', id: 305, fields: 1},
```

2020-07-08 10:33 UTC, thetommes approved these changes

2020-07-08 10:36 UTC, merged