Features/thetommes/get attributes
csehlke/EiDiA pull request #42
Opened 2020-06-28 13:14 UTC by thetommes

List attributes in frontend based on the selected document-type

2020-06-28 14:57 UTC, csehlke requested changes
Ich hätte den Service im Backend in den Model Controler gepackt, nachdem es hier ja nur um Model Daten geht, ansonsen passt das

2020-06-28 14:57 UTC, csehlke commented on EiDiA_backend/src/controllers/upload.js
> +    AttributeTypeModel.find({'documentTypeId': req.params.selectedDocumentTypeId}) //Condition
- ist diese Methode nicht besser im Model Controler aufgehoben?
- man sollte vielleicht auch abfangen, wenn kein Parameter mitgegeben wird, evtl. schmeißt sonst das Backend Fehler

Vielleicht an der Stelle einfach ne Abfrage ob der Parameter vorhanden ist und dann abhängig davon nur begrenzte AttributTypen zurückgeben

2020-06-28 16:02 UTC, thetommes commented on EiDiA_backend/src/controllers/upload.js
> +    AttributeTypeModel.find({'documentTypeId': req.params.selectedDocumentTypeId}) //Condition
![404](https://user-images.githubusercontent.com/26249618/85952329-c6b96e80-b968-11ea-968d-ff05c0b40507.PNG)
Ohne parameter bekommt man ein 404 zurück.

Ohne Parameter kann aus EiDiA keine Anfrage stattfinden, weil man ohne ausgewählten Dokumententypen garnicht in die Attribute-View kommt. Macht finde ich wenig Sinn, das extra nochmals zu prüfen. Was meinst du?

2020-06-28 17:55 UTC, csehlke requested changes

2020-06-28 17:55 UTC, csehlke commented on EiDiA_backend/src/controllers/model.js
> +    listAttributes
`listAttrbuteTypesByDocumentId` ?

2020-06-28 17:55 UTC, csehlke commented on EiDiA_backend/src/controllers/model.js
> +    AttributeTypeModel.find({'documentTypeId': req.params.selectedDocumentTypeId})
was spricht gegen so etwas vor allem anderen?
```
if (!Object.prototype.hasOwnProperty.call(req.params, 'selectedDocumentTypeId')) {
        return res.status(400).json({
            error: 'Bad Request',
            message: 'The request parameter must contain a selectedDocumentTypeId property',
        });
    }
```

2020-06-28 21:17 UTC, thetommes commented on EiDiA_backend/src/controllers/model.js
> +    AttributeTypeModel.find({'documentTypeId': req.params.selectedDocumentTypeId})
Funktioniert so nicht. Sobald die API Route ohne Parameter aufgerufen wird kommt die 404-Response. Der Request wird zu dem Zeitpunkt gar nicht mehr geprüft.

Falls du es doch zum Laufen bekommst, gerne einfach pushen.
[Sowas](https://stackoverflow.com/questions/46602707/express-route-not-getting-called-when-url-param-is-not-passed) würde funktionieren, aber ich denke jeden edge-case müssen wir nicht abfangen.

2020-06-29 08:12 UTC, csehlke approved these changes

2020-06-29 08:50 UTC, merged