search backend
csehlke/EiDiA pull request #53
Opened 2020-06-29 18:41 UTC by csehlke

based on #45  and #27 

Suche Funktioniert

TODO:
- Database output in "Table" Format umwandeln => done in #58

2020-07-01 10:11 UTC, thetommes requested changes
Siehe Kommentar

2020-07-01 10:11 UTC, thetommes commented on EiDiA_backend/src/models/document.js
> +    attributes: [
In meinem Branch habe ich das Schema so definiert:


```suggestion
    attributes: [
        {
            attributeId: {
                type: mongoose.Schema.Types.ObjectId,
                required: true,
                index: true,
            },
            value: {}
        },
    ],
});
```
Das Schema ist passend für POST-Requests, die so definiert sind:
`{
    "attributeData": [{"attributeId": "5ef9e3d2c4664e04e4003999", "value": "testText1"}, {"attributeId": "5ef9e3d2c4664e04e4003999", "value": "testText2"}]
}`

So war das doch eigentlich gedacht, oder?

2020-07-01 13:05 UTC, thetommes commented on EiDiA_backend/src/models/document.js
> +    attributes: [
Siehe #54

2020-07-04 14:20 UTC, csehlke commented
- [ ] merge #27 first
- [ ] set target branch to master

2020-07-15 15:26 UTC, thetommes approved these changes

2020-07-15 15:46 UTC, closed without merging