Cabinet/record
csehlke/EiDiA pull request #62
Opened 2020-07-08 10:00 UTC by bockph

Neuer Pull Request für record feature
-> enthält jetzt das gesamte sammelsurium an alten branches die jetzt gelöscht sind

still WIP, kann gemerged werden sobald ich es entferne

2020-07-12 18:59 UTC, csehlke requested changes
rest folgt wohl morgen

2020-07-12 18:59 UTC, csehlke commented on EiDiA_frontend/src/App.js
> +                        <FileCabinetView title={this.state.pageTitle}
sollte diese Componente nicht unter /browse stehen und hier die RecordView

2020-07-12 18:59 UTC, csehlke commented on EiDiA_frontend/src/App.js
> +                                <RecordView title={this.state.pageTitle}
müsste man der RecordView nicht mitgeben, welcher record angezeigt werden soll? basierend auf :id

2020-07-12 18:59 UTC, csehlke commented on EiDiA_frontend/src/components/Sidebar.js
> +                        <ListItemText primary={"Cabinet"}/>
gibt es einen Grund warum nicht Browse?

2020-07-12 18:59 UTC, csehlke commented on EiDiA_frontend/src/components/SmartDropDownBox.js
> +    preselectedValue: PropTypes.object
```suggestion
    preselectedValue: PropTypes.object.
    margin: PropTypes.string,
```

2020-07-12 18:59 UTC, csehlke commented on EiDiA_frontend/src/components/StyleElements.js
> +`;
magst du das hier noch einheitlich einrücken?

2020-07-13 08:55 UTC, bockph commented on EiDiA_frontend/src/App.js
> +                                <RecordView title={this.state.pageTitle}
ne das funktioniert innerhalb von RecordView über nen withRouter HOC Wrapper, kann dann innerhalb von RecordView mit this.props.match.params.id abgerufen werden

2020-07-13 08:56 UTC, bockph commented on EiDiA_frontend/src/components/Sidebar.js
> +                        <ListItemText primary={"Cabinet"}/>
Ne das hat sich nur vom Anfang her mitgeschleift..

2020-07-13 09:01 UTC, bockph commented on EiDiA_frontend/src/components/StyleElements.js
> +`;
Würde da jetzt erstmal nichts mehr machen, wollen ja die Styles eh noch komplett überarbeiten

2020-07-13 09:01 UTC, csehlke commented
![grafik](https://user-images.githubusercontent.com/29836078/87285765-35193780-c4f8-11ea-87ec-c0939ff1902b.png)

2020-07-13 09:03 UTC, csehlke commented
> 
> 
> ![grafik](https://user-images.githubusercontent.com/29836078/87285765-35193780-c4f8-11ea-87ec-c0939ff1902b.png)

Einfachste Lösung wäre den Footer zu entfernen :D

2020-07-13 09:16 UTC, bockph commented on EiDiA_frontend/src/App.js
> +                        <FileCabinetView title={this.state.pageTitle}
erledigt

2020-07-13 10:21 UTC, csehlke requested changes
File Explorer Part

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/components/record/RecordSymbol.js
> +"use strict";
merge with ../fileCabinet/RecordSymbol

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/views/FileCabinetView.js
> +        this.setState({search: event.target.value.substr(0, 20)});
warum nicht auf die komplete Eingabe, was für einen Mehrwert hat es die Suche auf die ersten 20 Zeichen der Eingabe zu beschränken?

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/views/FileCabinetView.js
> +                        inputProps={{'aria-label': 'description'}}
`description` ist eine gute  Beschreibung, warum nicht einfach die Zeile raus lassen?

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/views/FileCabinetView.js
> +            <Page title={"File Cabinet"}>
```suggestion
            <Page>
```

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/views/FileCabinetView.js
> +                        inputProps={{'aria-label': 'description'}}
```suggestion
```

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/views/FileCabinetView.js
> +                            to={"/record"}>
```suggestion
                    {filteredRecords.map((record, i) =>
                        <Link
                            key={i}
                            to={"/record/" + record.id}>
```
damit man zum richtigen record linkt

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/views/RecordView.js
> +        // this.setState(this.state);
```suggestion
        this.setState({currentPage: value})
```

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/App.js
> +                    )
hier fehlt der Authenticated Part

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/App.js
> +                                <RecordView title={this.state.pageTitle}
ok, spricht was dagegen, wenn man dann von `/record exact=true` nach browse weiterleitet?

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/components/record/FileExplorer.js
> +        element.active === true ?
magst du irgendwo noch commentieren was active heißt? nur durch das Backendschema weiß ich dass es sich um FolderOpened handelt, warscheinlich reicht auch einfach ein renaming

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/components/record/FileExplorer.js
> +                    </ElementDropTarget>
kann man hier nochmal eine Unterscheidung einbauen, dass nur Order ein DropTarget bekommen (evtl sogar mit einem Attribute das aus dem Backend kommt, dann kann man das da auch recht einfach für die Searchresults ausschalten), denn aktuell passiert nichts wenn ich ein Element auf einem File droppe, was ja auch richtig ist

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/components/record/filetable/ElementDropTarget.js
> +                backgroundColor: isOver ? 'rgba(28, 166, 166,0.3)' : ''
```suggestion
                backgroundColor: isOver && canDrop ? 'rgba(28, 166, 166,0.3)' : ''
```
braucht evl noch mehr changes in der Datei, damit das funktioniert

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/components/record/FileExplorer.js
> +        element.active === true ?
evtl ist auch schon die Lösung in ElemenetDropTable

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/components/record/filetable/Element.js
> +                <Grid container spacing={2} style={{cursor: (this.props.type === 'FOLDER') && 'pointer'}}
der style funktioniert nicht, da this.props.typ===undefined, heißt also drüber fehlt der Input, dann gehts
```suggestion
                <Grid container spacing={2} style={{cursor: (this.props.type === 'Folder') && 'pointer'}}
```

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/components/record/filetable/Element.js
> +                <Grid container spacing={2} style={{cursor: (this.props.type === 'FOLDER') && 'pointer'}}
oder alternativ
```suggestion
                <Grid container spacing={2} style={{cursor: (this.state.elementData.type === 'Folder') && 'pointer'}}
```

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/components/record/filetable/ElementSymbol.js
> +            case fileTypes.FOLDER:
nachdem wir aktuell nur Bilder hochladen können, wäre es hier sicher gut auch den case Image zu haben

2020-07-13 10:21 UTC, csehlke commented on EiDiA_frontend/src/components/record/filetable/Element.js
> +                            {this.state.elementData.name}
Abstand Symbol <-> Titel
```suggestion
                            &nbsp;&nbsp;{this.state.elementData.name}
```

2020-07-13 10:29 UTC, csehlke commented
```
Uncaught TypeError: a2 is undefined
    mergeByDate GraphsWidget.js:125
    mergeByDate GraphsWidget.js:125
    getData GraphsWidget.js:132
    createGraph GraphsWidget.js:93
    render GraphsWidget.js:139
    React 11
    unstable_runWithPriority scheduler.development.js:653
```
wenn ich einen neuen Graph erzeugen will mit
![grafik](https://user-images.githubusercontent.com/29836078/87295252-369d2c80-c505-11ea-9d77-a6a3cc759985.png)

EDIT: passiert nur wenn nur ein Wert fr den Graph angegeben wird

2020-07-13 10:31 UTC, csehlke commented
![grafik](https://user-images.githubusercontent.com/29836078/87294886-afe84f80-c504-11ea-8583-30b70ac40763.png)
ich wähle drei Attribute aus

![grafik](https://user-images.githubusercontent.com/29836078/87294929-c098c580-c504-11ea-871b-d77c60f7a887.png)
bekomme aber mehr angezeigt

2020-07-13 10:36 UTC, csehlke commented
abgeschnitten ohne scrollbar
![grafik](https://user-images.githubusercontent.com/29836078/87295453-7e23b880-c505-11ea-8df3-72808f133fee.png)

2020-07-13 10:42 UTC, csehlke commented
zum IndicatorWidgit
Wenn man hier die Anzahl auf 4 beschränkt schiebt sich das nicht unter ein anderes Widget
![grafik](https://user-images.githubusercontent.com/29836078/87295920-3f423280-c506-11ea-95b6-39f28687dfd1.png)

2020-07-13 11:39 UTC, csehlke requested changes
Everything but EditDialog

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Dashboard.js
> +        this.cells = [[0, 0, 0],
ist das nicht auch part of state?

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Dashboard.js
> +        return LogEntries.filter(entries => entries.recordId == this.state.recordId)
```suggestion
        return LogEntries.filter(entries => entries.recordId === this.state.recordId)
```

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Dashboard.js
> +            position: 'fixed',
```suggestion
            top: 'auto',
            bottom: '2em',
            right: '2em',
            left: 'auto',
            position: 'fixed',
```

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Dashboard.js
> +                    <FiEdit size={32}/>
was hältst du von der Idee das Icon zu einem X zu ändern wärend man editiert

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/Widget.js
> +    }
unused code

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/Widget.js
> +    MainPart() {
```suggestion
    renderMainPart() {
```

und dann genauso unten angepasst

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/Widget.js
> +            dashboardEditingActive: this.props.dashboardEditingActive,
gibt es einen Grund das in den State zu duplizieren?

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/LogWidget.js
> +            logCount: 5,
ist das das Maximum, sodass dieses Widget nicht größer wird als das Graph Widget?

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/IndicatorWidget.js
> +                .filter(attr => attr.attrId === mapping.attrId)
warum ist der Filter nötig, sollte es nicht eh nur einen Wert aus dem Backend geben?

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/IndicatorWidget.js
> +                    // return foundAttribute
```suggestion
```

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/IndicatorWidget.js
> +            <IndicatorElement elementPercentage={this.state.elementPercentage} key={index}>
elementPercentage wird nicht genutzt im IndicatorElement

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +
should we remove the pie chart completely?

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +            a1.map(itm => Object.assign(itm, a2.find((item) => (item.date === itm.date)))
first check if both exist to pevent crash

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +        )
warum nicht default option des Switch statements?

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +            case GraphType.line:
**l**ine vs. **B**ar

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +        let tmp = JSON.parse(JSON.stringify(Attributes));
tmp ist ein schlechter Name wie wäre es mit rawData?

2020-07-13 11:39 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +         * - make it stable: right now, if only one attribute mapping currently it crashes, if >2 the extra attributes are ignored
simplest fix wound be to restrict the user to max two inputs

2020-07-13 14:26 UTC, csehlke requested changes

2020-07-13 14:26 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/EditDialog.js
> +import {IoMdAddCircleOutline, IoMdRemoveCircleOutline} from "react-icons/io/index";
```suggestion
import {IoMdAddCircleOutline, IoMdRemoveCircleOutline} from "react-icons/all";
```

2020-07-13 14:26 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/EditDialog.js
> +                <DialogTitle key={"title"} style={classes.title} id="simple-dialog-title">
```suggestion
                <DialogTitle key={"title"} style={classes.title}>
```

2020-07-13 14:26 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/EditDialog.js
> +                <DialogContent key={"content"} style={{overflow: "hidden"}}>
warum `overflow: "hidden"`?

2020-07-13 14:26 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/EditDialog.js
> +                this.state.selectedAttributeMapping.length <= 5 ? this.getAddAttributeLineButton(12) : null
make this 4 so it won't grow bigger than the other widgets

2020-07-13 14:26 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/EditDialog.js
> +            {name: "green", color: "green"},
```suggestion
            {name: "Green", color: "green"},
```

2020-07-13 14:26 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/EditDialog.js
> +                this.state.selectedAttributeMapping.length <= 5 ? this.getAddAttributeLineButton(12) : null
make this one limited to 2 so we do not run in the rendering problem

2020-07-13 14:26 UTC, csehlke commented on EiDiA_frontend/src/components/record/Widgets/EditDialog.js
> +            displayName: null,
```suggestion
            displayName: '',
```
to get rid of error
```
Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    in input (created by ForwardRef(InputBase))
    in div (created by ForwardRef(InputBase))
    in ForwardRef(InputBase) (created by WithStyles(ForwardRef(InputBase)))
    in WithStyles(ForwardRef(InputBase)) (created by ForwardRef(OutlinedInput))
    in ForwardRef(OutlinedInput) (created by WithStyles(ForwardRef(OutlinedInput)))
    in WithStyles(ForwardRef(OutlinedInput)) (created by ForwardRef(TextField))
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ForwardRef(TextField))
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by EditDialog)
    in div (created by ForwardRef(Grid))
```

2020-07-13 14:26 UTC, csehlke commented on EiDiA_frontend/src/components/SmartDropDownBox.js
> +            value: this.props.preselectedValue
fix the warning:
```suggestion
            value: this.props.preselectedValue ? this.props.preselectedValue : null,
```

maybe better to rename prop to `value`

2020-07-13 14:26 UTC, csehlke commented on EiDiA_frontend/src/components/SmartDropDownBox.js
>                                 variant="outlined" placeholder="Type to filter"/>
```suggestion
                               variant="outlined" placeholder="Type to filter"
                getOptionSelected={(option, value) => option.id === value.id && option.name === value.name}/>
```

2020-07-13 17:52 UTC, bockph commented on EiDiA_frontend/src/views/FileCabinetView.js
> +        this.setState({search: event.target.value.substr(0, 20)});
keinen ist raus

2020-07-13 17:54 UTC, bockph commented on EiDiA_frontend/src/views/FileCabinetView.js
> +                        inputProps={{'aria-label': 'description'}}
copy & paste und so.... ist raus

2020-07-13 17:55 UTC, bockph commented on EiDiA_frontend/src/views/FileCabinetView.js
> +            <Page title={"File Cabinet"}>
dito

2020-07-13 18:01 UTC, bockph commented on EiDiA_frontend/src/App.js
> +                    )
erledigt

2020-07-13 18:07 UTC, bockph commented on EiDiA_frontend/src/components/record/FileExplorer.js
> +        element.active === true ?
erledigt

2020-07-13 18:39 UTC, bockph commented on EiDiA_frontend/src/components/record/FileExplorer.js
> +                    </ElementDropTarget>
habs innerhalb vom DropTarget gelöst, dass es nicht "angezeigt" wird bzw, der style entfernt wird

2020-07-13 18:43 UTC, bockph commented on EiDiA_frontend/src/components/record/filetable/ElementDropTarget.js
> +                backgroundColor: isOver ? 'rgba(28, 166, 166,0.3)' : ''
indeed die bessere Lösung...

2020-07-13 18:46 UTC, bockph commented on EiDiA_frontend/src/components/record/filetable/Element.js
> +                <Grid container spacing={2} style={{cursor: (this.props.type === 'FOLDER') && 'pointer'}}
erledigt mit this.state.elementData.type===fileTypes.Folder

2020-07-13 18:46 UTC, bockph commented on EiDiA_frontend/src/components/record/filetable/ElementSymbol.js
> +            case fileTypes.FOLDER:
case image?

2020-07-13 20:07 UTC, bockph commented on EiDiA_frontend/src/components/record/Dashboard.js
> +        this.cells = [[0, 0, 0],
ne ist ne reine helper variable, aber hast recht das hat auch nichts mehr als class attribute zu suchen, habs in die Methode reingeschoben

2020-07-13 20:10 UTC, bockph commented on EiDiA_frontend/src/components/record/Dashboard.js
> +        return LogEntries.filter(entries => entries.recordId == this.state.recordId)
erledigt, ging bis dato nicht, da recordid auf der einen seite n string und auf der anderen number vom typ war

2020-07-13 20:12 UTC, bockph commented on EiDiA_frontend/src/components/record/Dashboard.js
> +                    <FiEdit size={32}/>
wollte den Button mit zwei unterschiedlichen Farben machen, habe ich aber nicht weiter verfolgt weil die styles noch fehlen...

2020-07-13 20:14 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/Widget.js
> +    }
erledigt

2020-07-13 20:15 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +            a1.map(itm => Object.assign(itm, a2.find((item) => (item.date === itm.date)))
ich weiß das hier noch fehler drinnen sind, möchte das aber im Backendhandlen deswegen habe ich es nicht weiter bearbeitet

2020-07-13 20:18 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +        )
erledigt

2020-07-13 20:21 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +            case GraphType.line:
lol, ist nur durchgegangen weil als default linechart eingestellt war

2020-07-13 20:22 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +        let tmp = JSON.parse(JSON.stringify(Attributes));
wie oben, die methode wird eh durchs backend ersetzt

2020-07-13 20:22 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/GraphsWidget.js
> +         * - make it stable: right now, if only one attribute mapping currently it crashes, if >2 the extra attributes are ignored
siehe oben

2020-07-13 20:24 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/EditDialog.js
> +                <DialogContent key={"content"} style={{overflow: "hidden"}}>
verhindert ne unnötige scrollbar

2020-07-13 20:25 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/EditDialog.js
> +                this.state.selectedAttributeMapping.length <= 5 ? this.getAddAttributeLineButton(12) : null
müssen wir nochmal ne bessere Lösung finden, bei nem hochauflösenden bildschirm sähe das ein bisschen komisch aus

2020-07-13 20:28 UTC, bockph commented on EiDiA_frontend/src/components/SmartDropDownBox.js
> +            value: this.props.preselectedValue
wieso die condition? wenn props leer sind haben sie eh den wert null

2020-07-14 06:09 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/IndicatorWidget.js
> +            <IndicatorElement elementPercentage={this.state.elementPercentage} key={index}>
erledigt

2020-07-14 06:11 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/IndicatorWidget.js
> +                .filter(attr => attr.attrId === mapping.attrId)
das Widget enthält ein Mapping welche Attribute es verwendet, das Dashboard hingegen bekommt !alle! Attribute. Evtl. ändert sich das nochmal mit dem Backend

2020-07-14 06:16 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/LogWidget.js
> +            logCount: 5,
ja

2020-07-14 06:23 UTC, bockph commented on EiDiA_frontend/src/components/record/Widgets/Widget.js
> +            dashboardEditingActive: this.props.dashboardEditingActive,
was genau? Soweit ich das verstanden habe sollten alle properties die sich ggbfls. ändern in den state wandern

2020-07-14 06:50 UTC, csehlke requested changes

2020-07-14 06:50 UTC, csehlke commented on .gitignore
> +/package-lock.json
laut npm doku soll das commited werden

2020-07-14 06:50 UTC, csehlke commented on EiDiA_frontend/src/App.js
> +                this.getRoute('/record', RecordView, true), //TODO<- this should later be deleted
mach doch ein redirekt draus

2020-07-14 06:50 UTC, csehlke commented on EiDiA_frontend/src/App.js
> +                this.getRoute('/record/:id', RecordView, false),
warum soll das keine Auth benötigen?

2020-07-14 06:53 UTC, csehlke approved these changes

2020-07-14 06:57 UTC, merged