Features/thetommes/record picker
csehlke/EiDiA pull request #71
Opened 2020-07-15 15:23 UTC by thetommes

- Recordpicker und Fileexplorer in Dialog hinzugefügt

Dokumente mit parentFolderId: "000000000000000000000000" und fileType: "Folder" sind Root-Ordner.

2020-07-15 15:26 UTC, csehlke requested changes
magst du dann das #53 approven, nachdem das ja auch in deinem Branch mit drinnen steckt?

2020-07-15 15:26 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +};*/
```suggestion
```

2020-07-15 15:29 UTC, thetommes commented
And die Reviewer: Momentan gibt es nur in der "Amazon"-Akte Folder

2020-07-15 19:55 UTC, csehlke commented
eng.traineddata entfernen und dann zu gitignore hinzufügen

2020-07-15 20:30 UTC, csehlke requested changes
warum ist deine parentID mit so vielen 0en, braucht man die damit es zu einer ObjectId für die Datenbank wird? würde es dann nicht ausreichen im Backend zu testen ob parentID=0 und dann die Id auf diese vielen 0en setzten?

2020-07-15 20:30 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +        .then(documentList => {
```suggestion
        .then(documentList => {
            documentList.sort((a, b) => {
                return ('' + a.name).localeCompare(b.name);
            });
```

2020-07-15 20:30 UTC, csehlke commented on EiDiA_backend/src/models/document.js
> +        enum: ['Folder', 'PDF', 'Word', 'Image', ''],
nimm doch hier das Konstanen-Array

2020-07-15 20:30 UTC, csehlke commented on EiDiA_backend/src/routes/record.js
> +// router.get('/document/list/types/:recordId', middleWares.checkAuthentication, ModelController.listDocumentTypes);
???

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/assets/Constants.js
> +        name: "Sample Tom Folder",
warum?

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/AttributeContainer.js
> +            fileType: "Image" // EiDiA currently only supports uploading scanned images
nimm die Constante

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/uploadFiletable/RecordSymbol.js
> +import React from 'react';
kannst du hier nicht einfach die Datei aus dem fileExplorer nutzen, oder was ist an der hier anders?

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/uploadFiletable/UploadFileExplorer.js
> +                {this.state.elements.map((element, index) => element.parentFolderId === '000000000000000000000000' ?
```suggestion
                {this.state.elements.map((element, index) => element.parentFolderId === '0' ?
```

2020-07-15 20:30 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +        }
list sollte doch ein get request sein, heißt der body ist leer und die parameter kommen über die query

und dann kann das hier nicht funktionieren, wenn im Mapping zwei elemente hat, dann ist die MongoDB query nämlich wiedersprüchlich, denn dann hast du eine & Verknüpfung

2020-07-15 20:30 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +                    fileType: document.fileType, //TODO: implement filetype in database
```suggestion
                    fileType: document.fileType,
```
an der Stelle ist auch in Zukunft nichts zu tun

2020-07-15 20:30 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +                    lastModifiedOnDate: document.lastModifiedOnDate,
musst du formatieren, sonst kann das im Frontend nicht angezeigt werden
`format(document.createdOnDate, 'dd/MM/yyyy')`

2020-07-15 20:30 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +                    lastModifiedOnDate: document.lastModifiedOnDate,
```suggestion
                    createdOnDate: format(document.createdOnDate, 'dd/MM/yyyy'),
                    lastModifiedOnDate: format(document.lastModifiedOnDate, 'dd/MM/yyyy'),
```

2020-07-15 20:30 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +        }
bsp sind beim Search zu finden

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/uploadFiletable/Element.js
> +const drag = DragSource(DragTypes.ELEMENT, itemSource, collectDrag); //needed for react-dnd
warum muss das dragable sein?

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/RecordPickerDialog.js
> +    max-height: 40vh;
gerne auch etwas größer, hab das gefühl dass das sehr frimelig/klein ist

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/RecordPickerDialog.js
> +            selectedFolder: {name: 'Root-Folder', id: '000000000000000000000000'},
root elemente haben bei uns bis jetzt immer die `parentId: 0` in den Frontendtabellen und evtl (bin mir nicht sicher ob das schon jemand implementiert hat) `parentId: recordId` im backend und der Datenabank

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/RecordPickerDialog.js
> +            selectedFolder: {name: 'Root-Folder', id: '000000000000000000000000'}, //Reset state after close
same here

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/uploadFiletable/Element.js
> +                    <Grid item xs={12} sm={4}>
warum sm={4}?
```suggestion
                    <Grid item xs={12} sm={12}>
```
sonst wird der Text nicht auf voller Breite angezeigt

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/uploadFiletable/UploadFileExplorer.js
> +            });
warum nicht im Backend machen? siehe https://github.com/csehlke/EiDiA/pull/58/files#diff-b7471bfdd8cb3eee2928db802a78c018R231

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/uploadFiletable/UploadFileExplorer.js
> +    }
warum muss ich für einen Ordner einen neuen Parent setzten? Das ist glaub ein Teil vom DnD

2020-07-15 20:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/uploadFiletable/UploadFileExplorer.js
> +                <Grid item xs={12} sm={4}>
```suggestion
                <Grid item xs={12} sm={12}>
```

2020-07-16 06:35 UTC, thetommes commented on EiDiA_backend/src/controllers/record.js
> +        }
Ist glaube ich noch WIP von @bockph 
Für mein Dropdown ist nur "listDocumentByRecordId" relevant

2020-07-16 06:35 UTC, thetommes commented on EiDiA_backend/src/controllers/record.js
> +        .then(documentList => {
same

2020-07-16 06:35 UTC, thetommes commented on EiDiA_backend/src/routes/record.js
> +// router.get('/document/list/types/:recordId', middleWares.checkAuthentication, ModelController.listDocumentTypes);
WIP von @bockph, kann von mir aus raus

2020-07-16 06:35 UTC, thetommes commented on EiDiA_frontend/src/assets/Constants.js
> +        name: "Sample Tom Folder",
Dummy-Daten. Nehmen wir am Schluss komplett raus

2020-07-16 06:35 UTC, thetommes commented on EiDiA_frontend/src/components/upload/uploadFiletable/RecordSymbol.js
> +import React from 'react';
Geht nicht so einfach mit der Formatierung im RecordBrowser, habe deswegen die Datei von Philipp übernommen und nur die font-size angepast

2020-07-16 09:05 UTC, thetommes commented on EiDiA_frontend/src/components/upload/uploadFiletable/UploadFileExplorer.js
> +                {this.state.elements.map((element, index) => element.parentFolderId === '000000000000000000000000' ?
Daten kommen hier vom Backend (in dem die 24 Nullen stehen). Hier muss man also prüfen

2020-07-16 10:58 UTC, csehlke requested changes

2020-07-16 10:58 UTC, csehlke commented on EiDiA_backend/src/controllers/upload.js
> +let parentFolderId;
warum die variabel deklaration über allem? macht das nicht mehr sinn die in der Methode zu definieren?

2020-07-16 10:58 UTC, csehlke commented on EiDiA_frontend/src/components/upload/uploadFiletable/UploadFileExplorer.js
> +                {this.state.elements.map((element, index) => element.parentFolderId === '000000000000000000000000' ? //24x 0 comes from backend (valid ObjectId)
sollte man dann nicht auch wieder im Backend `0` darus amchen?

2020-07-16 10:58 UTC, csehlke commented on EiDiA_backend/src/routes/record.js
> +//TODO Add authentication middleware
```suggestion
```

2020-07-16 10:58 UTC, csehlke commented on EiDiA_backend/src/routes/record.js
> +router.get('/document/listfolders/:recordId', RecordController.listFoldersByRecordId);
```suggestion
router.get('/document/listfolders/:recordId', middleWares.checkAuthentication, RecordController.listFoldersByRecordId);
```

2020-07-16 10:58 UTC, csehlke commented on EiDiA_frontend/src/components/upload/NewDocumentTypeDialog.js
>  `;
```suggestion
    max-height: 40vh;
`;
```

2020-07-16 10:58 UTC, csehlke commented on EiDiA_frontend/src/components/upload/NewDocumentTypeDialog.js
>      max-width: 40vw;
```suggestion
    min-width: 40vw;
    max-width: 40vw;
```

2020-07-16 10:58 UTC, csehlke commented on EiDiA_frontend/src/components/upload/NewDocumentTypeDialog.js
>      max-width: 40vw;
Warum rausgenommen?

2020-07-16 10:58 UTC, csehlke commented on EiDiA_frontend/src/components/upload/TypePicker.js
> +                      style={{minHeight: "58vh"}}>
warum?

2020-07-16 10:58 UTC, csehlke commented on EiDiA_frontend/src/components/upload/uploadFiletable/UploadFileExplorer.js
> +
ehh??

```suggestion
            this.setState({
                elements: data.documents,
            });
```

2020-07-16 10:58 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +                    parentFolderId: document.parentFolderId,
```suggestion
                    parentFolderId: document.parentFolderId === '000000000000000000000000' ? 0 : document.parentFolderId,
```

2020-07-16 15:43 UTC, thetommes commented on EiDiA_frontend/src/components/upload/uploadFiletable/UploadFileExplorer.js
> +
War früh am Morgen 😁

2020-07-16 15:47 UTC, thetommes commented on EiDiA_frontend/src/components/upload/NewDocumentTypeDialog.js
>  `;
Ohne max-height fängt der Dialog erst an zu scrollen, wenn der Bildschirm mit neuen Attributen voll ist.
Ansichtssache, was schöner ist. Ich nehm das mal mit rein

2020-07-16 15:50 UTC, thetommes commented on EiDiA_frontend/src/components/upload/NewDocumentTypeDialog.js
>      max-width: 40vw;
Deswegen:
![screenshot](https://user-images.githubusercontent.com/26249618/87692997-b852bb80-c78c-11ea-90da-373fe6c2f724.png)

2020-07-16 15:51 UTC, thetommes commented on EiDiA_frontend/src/components/upload/TypePicker.js
> +                      style={{minHeight: "58vh"}}>
Ohne die minHeight rutschen bei mir nach Upload eines Dokuments sämtliche Buttons/Textfelder im Typepicker ein paar Pixel nach unten. Kannst du das so bestätigen?

2020-07-16 18:29 UTC, csehlke commented on EiDiA_frontend/src/components/upload/NewDocumentTypeDialog.js
>      max-width: 40vw;
sollte nu gefixed sein, kam da ein dialog eine maxWidth by default hat und die wollen wir ja hier nicht

2020-07-16 18:30 UTC, csehlke commented on EiDiA_frontend/src/components/upload/TypePicker.js
> +                      style={{minHeight: "58vh"}}>
ne kann ich nicht bestätigen, hab da aber nochmal etwas rumgeschraubt

2020-07-16 19:18 UTC, csehlke approved these changes

2020-07-16 19:25 UTC, merged