Features/thetommes/recent files
csehlke/EiDiA pull request #73
Opened 2020-07-17 10:01 UTC by thetommes

In den Recentfiles werden Akten angezeigt, deren Dokumente ein "lastModifiedOnDate" in den letzten sieben Tagen hatten

2020-07-18 07:44 UTC, csehlke requested changes

2020-07-18 07:44 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +        'createdBy': req.userId, 'fileType': fileTypes.IMAGE, 'lastModifiedOnDate': {
```suggestion
        'createdBy': req.userId, 'fileType': {$ne fileTypes.FOLDER}, 'lastModifiedOnDate': {
```

2020-07-18 07:44 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +            $gte: new Date(new Date() - 7 * 60 * 60 * 24 * 1000) //only look for documents that were modified in the last week
evtl ist es möglich zu sortieren und dann die top 5 aus zu geben, dann haben wir im Frontend immer 5 Folder und nicht undefiniert viele

2020-07-18 10:48 UTC, csehlke requested changes

2020-07-18 10:48 UTC, csehlke commented on EiDiA_frontend/src/components/welcome/RecentFiles.js
> +        })
```suggestion
        }).catch(error => {
            console.log(error);
        });
```

2020-07-18 10:48 UTC, csehlke commented on EiDiA_frontend/src/components/welcome/RecentFiles.js
> +            selectedRecord: ''
```suggestion´
```

für was braucht man das?

2020-07-18 10:48 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +            $gte: new Date(new Date() - 7 * 60 * 60 * 24 * 1000) //only look for documents that were modified in the last week
```suggestion
        'createdBy': req.userId,
        'fileType': {$ne: fileTypes.FOLDER},
        'lastModifiedOnDate': {
            $gte: new Date(new Date() - 7 * 60 * 60 * 24 * 1000) //only look for documents that were modified in the last week
```

2020-07-18 10:48 UTC, csehlke commented on EiDiA_backend/src/controllers/record.js
> +        'createdBy': req.userId, 'fileType': {$ne: fileTypes.FOLDER}, 'lastModifiedOnDate': {
von allen oder nur von mir erstellte Documente?
was ist mit updatedBy evtl. brauchen wir dann auch dieses Attribute

ich wäre jetzt erstmal die Einschränkung 'createdBy': req.userId rausgenommen

2020-07-18 11:04 UTC, thetommes commented on EiDiA_frontend/src/components/welcome/RecentFiles.js
> +            selectedRecord: ''
Wozu braucht man was?

2020-07-18 11:11 UTC, thetommes commented on EiDiA_backend/src/controllers/record.js
> +        'createdBy': req.userId, 'fileType': {$ne: fileTypes.FOLDER}, 'lastModifiedOnDate': {
Recent files sollen userspezifisch sein. createdBy ist momentan das einzige Feld dass userspezifisch gesetzt wird.
Wo haben wir ein Attribut "updatedBy"? Wäre mir neu.
Falls wir das haben, sollte das natürlich mit rein

2020-07-19 07:25 UTC, csehlke approved these changes

2020-07-19 07:35 UTC, csehlke commented
Die LOG generierung fehlt aktuell noch, oder?

2020-07-19 09:41 UTC, merged