Features/thien/doc type selector
csehlke/EiDiA pull request #78
Opened 2020-07-18 15:05 UTC by Neihtq

Hauptänderungen:
-  Select Template View: Such button im DocSearch eingefügt
-  Edit Template VIew (siehe Bild):
    - DocTypeSelector in Subcomponent 2
    - VariableList runter zu Subcomponent3

DocTypeSelector:

1. Dokumenttyp auswählen
2. Attributfeld ist enabled: Attribut auswählen
3. Copybutton ist enabled: drauf klicken und die SnackBar informiert, dass die Variable im Clipboard ist
4. Variable im DocEditor einfügen (CTRL+V) --> ausgewählter Dokumenttyp ist ausgegraut und kann nicht mehr geändert werden
5. "+ Add Another Document Type" lässt das ganze nochmal für einen weiteren Dokumententypen machen

![image](https://user-images.githubusercontent.com/22617511/87855387-3394a880-c918-11ea-9604-e1c39ffacd7a.png)

2020-07-18 16:50 UTC, Neihtq commented
Layout angepasst 
![image](https://user-images.githubusercontent.com/22617511/87857496-7ad66580-c927-11ea-8f79-fb1fae6ae145.png)

2020-07-18 17:01 UTC, csehlke requested changes

2020-07-18 17:01 UTC, csehlke commented on EiDiA_frontend/src/components/export/ExportMainView.js
> +            linkedDocTypes: [],
einmal ein Beispiel

2020-07-18 17:01 UTC, csehlke commented on EiDiA_frontend/src/components/export/ExportMainView.js
> +        }
für die TODO Liste, das Model muss im Backend auch entsprechend angepasst werden

2020-07-18 17:01 UTC, csehlke commented on EiDiA_frontend/src/components/export/selectTemplate/DocSearch.js
> +                               onKeyPress={this.search}/>
hier fehlt der Value, sodass ich auch über den Button den Wert abschicken kann

2020-07-18 17:01 UTC, csehlke commented on EiDiA_frontend/src/components/export/editTemplate/DocTypeSelector.js
> +            linkedDocTypes: [null],
gibts für das null einen Grund?

2020-07-18 17:01 UTC, csehlke commented on EiDiA_frontend/src/components/export/editTemplate/DocTypeSelector.js
> +            });
catch fehlt

2020-07-18 17:01 UTC, csehlke commented on EiDiA_frontend/src/components/export/editTemplate/DocTypeSelector.js
> +            <div style={{overflow: 'auto', maxHeight: '250px', minHeight: '250px'}}>
was hälst du davon die maxHeight relativ zur Seitengröße zu machen, also in vh

2020-07-18 17:01 UTC, csehlke commented on EiDiA_frontend/src/components/export/editTemplate/DocTypeSelector.js
> +        this.setState({linkedDocTypes: this.state.linkedDocTypes.concat(null)})
warum null

2020-07-18 17:33 UTC, Neihtq commented on EiDiA_frontend/src/components/export/ExportMainView.js
> +        }
im backend-branch hab ich bereits das objekt vom frontend an dem model vom backend angepasst.

2020-07-18 17:35 UTC, Neihtq commented on EiDiA_frontend/src/components/export/editTemplate/DocTypeSelector.js
> +        this.setState({linkedDocTypes: this.state.linkedDocTypes.concat(null)})
Platzalter für die neue DocTypeSelectorLine, siehe oben

2020-07-18 17:39 UTC, Neihtq commented on EiDiA_frontend/src/components/export/editTemplate/DocTypeSelector.js
> +            linkedDocTypes: [null],
Platzhalter für die DocTypeSelectorLine, damit die linkedDocTypes.length nicht 0 ist

2020-07-18 18:58 UTC, csehlke requested changes

2020-07-18 18:58 UTC, csehlke commented on EiDiA_frontend/src/components/export/editTemplate/DocTypeSelector.js
> +        console.log(this.state.linkedDocTypes);
```suggestion
```

2020-07-19 11:22 UTC, csehlke approved these changes

2020-07-19 12:53 UTC, merged